apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  containers:
  - image: webapp:tag
    name: webapp
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
